### ISSUE TITLE
Installation Issue README.md

### ISSUE THREAD

**Issue by joesoap99** [jamartinh/Orange3-Spark#8]
Python 3.5 Anaconda 4,1,1 64 bit Windows 8,1, Orange 3.3

Was trying to install add-on and got following error message concerning opus FC.
Do I need to install an additional module? :

"Collecting Orange3-spark
  Using cached Orange3-spark-0.2.6.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ROBERT~1\AppData\Local\Temp\pip-build-00_yromb\Orange3-spark\setup.py", line 41, in <module>
        LONG_DESCRIPTION = open('README.md').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
"

**Comment by kernc** [comment]
Right, Python doesn't include README.md in the source distribution archive by default, hence it is not available at install time. The project is [missing a MANIFEST.in file](https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute).

Until this is fixed, it might be possible to install the add-on by cloning the repository and running pip install from within the checkout.

**Comment by packet-rat** [comment]
I tried cloning the repo and installing with PIP within the checkout.  Although I have successfully installed the library, Orange3 is not seeing/recognizing the add-on.  Note that although I've used virtualenv, Canvas, and pyCharm for many years, I'm a complete NEWB with Anaconda.  I've tried conda-install but the outcome is still the same, Orange3 does not recognize the add-on.

Seems like the real fix is simply to add the MANIFEST.in file to this repo.  What's the quickest way to get this done?

**Comment by jamartinh** [comment]
Hello, could someone test if now it works ?

**Comment by joesoap99** [comment]
I have succesfully installed the widget on Orange 3.3.6 and Python 3.5
I have not had time to actually try out the new widget as yet.
When I clicked the PySpark script widget there was an error - see attached.

![spark](https://cloud.githubusercontent.com/assets/8518350/21505348/69e0028c-cc5e-11e6-97a1-d5b683b7a41a.png)
